name: fitness_scout
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

  # --- DEPENDENCIES

dependencies:
  flutter:
    sdk: flutter

  # --- ICONS
  iconsax: any
  cupertino_icons: ^1.0.6

  # --- STATE-MANAGEMENT
  get: any
  get_storage: ^2.1.1

  #  --- UTILITY PACKAGES
  intl: any
  smooth_page_indicator: ^1.1.0
  form_field_validator: ^1.1.0
  lottie: ^3.1.2
  connectivity_plus: ^2.3.4

  #  --- FIREBASE
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4

  # --- DEV DEPENDENCIES

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_native_splash:

  #  FOR CONSOLE ERRORS
  logger: any

flutter:

  uses-material-design: true

  #  --- ASSETS

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/logo/
    - assets/user_profile/
    - assets/splash_screen_logo/
    - assets/animation/

  #---------------- LOCAL FONTS ----------------

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800