name: fitness_scout
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

  # --- DEPENDENCIES

dependencies:
  flutter:
    sdk: flutter

  # --- ICONS
  iconsax: any
  cupertino_icons: ^1.0.6

  # --- STATE-MANAGEMENT
  get: any

  # --- DEV DEPENDENCIES

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  #  FOR CONSOLE ERRORS
  logger: any

flutter:

  uses-material-design: true

  #  --- ASSETS

  assets:
     - assets/fonts/
     - assets/icons/
     - assets/images/
     - assets/logo/
     - assets/user_profile

  #---------------- LOCAL FONTS ----------------

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800