---
name: fitness_scout
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  iconsax: any
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  shimmer: ^3.0.0
  get: any
  get_storage: ^2.1.1
  intl: any
  smooth_page_indicator: ^1.1.0
  form_field_validator: ^1.1.0
  connectivity_plus: ^2.3.4
  syncfusion_flutter_charts: ^27.1.53
  image_picker: ^1.1.2
  audioplayers: ^6.1.0
  syncfusion_flutter_gauges: null
  cached_network_image: ^3.4.0
  geolocator: ^10.0.0
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_markdown: ^0.7.1
  google_maps_flutter: ^2.6.1
  firebase_storage: ^11.7.7
  custom_info_window: ^1.0.1
  readmore: ^3.0.0
  mobile_scanner: ^6.0.2
  url_launcher: ^6.3.1
  mocktail: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.13.1
  logger: any
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/logo/
    - assets/user_profile/
    - assets/splash_screen_logo/
    - assets/animation/
    - assets/icon/
    - assets/images/food/
    - assets/artworks/
    - assets/images/qr_code/
    - assets/sounds/
    - assets/map_styles/
    - assets/map_styles/dark_map_style.json
    - assets/map_styles/light_map_style.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
