// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmy9ytXM6mI_qBZJBb5vjZhAzSO0aVQiE',
    appId: '1:660328340901:android:473db12114c25663335c4c',
    messagingSenderId: '660328340901',
    projectId: 'ecommerceapp-853cf',
    databaseURL: 'https://ecommerceapp-853cf-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-853cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEq8qnIRfv2b3tlrCm8lHy9JKcb3crY-g',
    appId: '1:660328340901:ios:86c57928a47f2c37335c4c',
    messagingSenderId: '660328340901',
    projectId: 'ecommerceapp-853cf',
    databaseURL: 'https://ecommerceapp-853cf-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-853cf.appspot.com',
    androidClientId: '660328340901-ub8aiajkcpvguojh89hd69p9qs74cc2b.apps.googleusercontent.com',
    iosClientId: '660328340901-bf6gq95ebmdvrqep8h1oaso65lbb7cft.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessScout',
  );
}
